export const NONEXISTINGCOMMAND = 'ERROR\r\n';
export const ERROR = 'ERROR\r\n';
export const CLIENTERROR = 'CLIENT_ERROR bad data\r\nERROR\r\n';
export const CLIENTERRORBADFORMAT = 'CLIENT_ERROR bad command line format\r\nERROR\r\n';
export const SERVERERROR = 'SERVER_ERROR <error>\r\n';
export const NOTSTORED = 'NOT_STORED\r\n';
export const CONTINUE = 'CONTINUE';
export const NOTFOUND = 'NOT_FOUND\r\n';
export const EXISTS = 'EXISTS\r\n';
